### ISSUE TITLE
2.4 available 

### ISSUE THREAD

**Issue by Justinzobel** [andrex4k/solus#1]
https://github.com/wine-compholio/wine-staging/releases :)

**Comment by andrex4k** [comment]
oh, I created it for an example as it is possible to make a package. to show at a forum. I wasn't going to support further as put solus simply to look what is it) I have no time for support in any else projects because work. Also there are 2 open source of the project in which I consist or I use. (gentoo and ubuntu) excuse for inconveniences or not to understanding.
